export const PortfolioImages = [
  {
    id: 775896846,
    name: "project-happy-thoughts-vite",
    prettyname: "Happy Thoughts",
    url: "../src/assets/Projectimages/happythoughts.png",
    webp: "../src/assets/Projectimages/happythoughts.webp",
  },
  {
    id: 770027347,
    name: "project-survey-vite",
    prettyname: "Pirate name generator",
    url: "../src/assets/Projectimages/pirate.png",
    webp: "../src/assets/Projectimages/pirate.webp",
  },
  {
    id: 765330479,
    name: "project-weather-app",
    prettyname: "Weather App",
    url: "../src/assets/Projectimages/weather.png",
    webp: "../src/assets/Projectimages/weather.webp",
  },
  {
    id: 767646855,
    name: "project-music-releases-vite",
    prettyname: "Music Releases",
    url: "../src/assets/Projectimages/musiclibrary.png",
    webp: "../src/assets/Projectimages/musiclibrary.webp",
  },
  {
    id: 758265166,
    name: "project-chatbot",
    prettyname: "Bobatea Chatbot",
    url: "../src/assets/Projectimages/bobateabot.png",
    webp: "../src/assetsPprojectimages/bobateabot.webp",
  },
  {
    id: 752318308,
    name: "project-pizza",
    prettyname: "Pizza Bytez",
    url: "../src/assets/Projectimages/pizzabytez.png",
    webp: "../src/assets/Projectimages/pizzabytez.webp",
  },
  {
    id: 740093160,
    name: "project-news-site",
    prettyname: "Veganomnomicon",
    url: "../src/assets/Projectimages/Veganomnomicon.png",
    webp: "../src/assets/projectimages/Veganomnomicon.webp",
  },
  {
    id: 759483271,
    name: "project-library",
    prettyname: "Book Library",
    url: "../src/assets/Projectimages/Booklibrary.png",
    webp: "../src/assets/Projectimages/Booklibrary.webp",
  },
];
