export const PortfolioImages = [
  {
    id: 775896846,
    name: "project-happy-thoughts-vite",
    prettyname: "Happy Thoughts",
    url: "../assets/Projectimages/happythoughts.jpg",
    webp: "../assets/Projectimages/happythoughts.webp",
  },
  {
    id: 770027347,
    name: "project-survey-vite",
    prettyname: "Pirate name generator",
    url: "../assets/Projectimages/pirate.jpg",
    webp: "../assets/Projectimages/pirate.webp",
  },
  {
    id: 765330479,
    name: "project-weather-app",
    prettyname: "Weather App",
    url: "../assets/Projectimages/weatherduo2DUOWEATHER-2.jpg",
    webp: "../assets/Projectimages/weatherduo2DUOWEATHER-2.webp",
  },
  {
    id: 767646855,
    name: "project-music-releases-vite",
    prettyname: "Music Releases",
    url: "../assets/Projectimages/musiclibrary.jpg",
    webp: "../assets/Projectimages/musiclibrary.webp",
  },
  {
    id: 758265166,
    name: "project-chatbot",
    prettyname: "Bobatea Chatbot",
    url: "../assets/Projectimages/teachat.jpg",
    webp: "../assets/Projectimages/teachat.webp",
  },
  {
    id: 752318308,
    name: "project-pizza",
    prettyname: "Pizza Bytez",
    url: "../assets/Projectimages/pizza.jpg",
    webp: "../assets/Projectimages/pizza.webp",
  },
  {
    id: 740093160,
    name: "project-news-site",
    prettyname: "Veganomnomicon",
    url: "../assets/Projectimages/veganews.jpg",
    webp: "../assets/Projectimages/veganews.webp",
  },
  {
    id: 759483271,
    name: "project-library",
    prettyname: "Book Library",
    url: "../assets/Projectimages/library.jpg",
    webp: "../assets/Projectimages/library.webp",
  },
  {
    id: 787542341,
    name: "project-labyrinth-zustand-vite",
    prettyname: "Labyrinth",
    url: "../assets/Projectimages/labyrint.jpg",
    webp: "../assets/Projectimages/labyrint.webp",
  },
  {
    id: 806681364,
    name: "project-final",
    prettyname: "eGo",
    url: "../assets/Projectimages/EGO.jpg",
    webp: "../assets/Projectimages/EGO.webp",
  },
  {
    id: 783405130,
    name: "project-todos-context-vite",
    prettyname: "Todo List",
    url: "../assets/Projectimages/task.jpg",
    webp: "../assets/Projectimages/task.webp",
  },
  {
    id: 790369291,
    name
      :
      "project-design-handoff-vite",
    prettyname: "Y Yoga Studio",
    url: "../assets/Projectimages/yoga.jpg",
    webp: "../assets/Projectimages/yoga.webp",
  },
];
